# Generated by Django 3.2 on 2025-02-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال پایان(در صورتی که پایان نداشته باشد خالی بگذارید)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_name',
            field=models.CharField(max_length=255, verbose_name='نام موسسه'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(verbose_name='سال شروع'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان(در صورتی که پایان نداشته باشد خالی بگذارید)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(verbose_name='سطح مهارت'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مهارت'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile', verbose_name='پروفایل'),
        ),
    ]
